apiVersion: "ember-csi.io/v1alpha1"
kind: "EmberCSI"
metadata:
  name: "external-ceph"
  namespace: ember-csi
spec:
  size: 1
  image: embercsi/ember-csi
  config:
    envVars:
      X_CSI_PERSISTENCE_CONFIG:       '{"storage":"crd"}'
      X_CSI_BACKEND_CONFIG :          '{"name": "rbd", "driver": "RBD", "rbd_user": "admin", "rbd_pool": "cephfs_data", "rbd_ceph_conf": "/etc/ceph/ceph.conf", "rbd_keyring_conf": "/etc/ceph/ceph.client.admin.keyring"}'
    sysFiles:
      name: system-files
      key: "system-files.tar"
