---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-sleep
spec:
  containers:
    - name: busybox-sleep
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: ember-csi-aio-pvc
